In [33]:
import numpy as np

## Матрицы и матричные операции. Часть 1

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;<br>

   AB - матрица не определена<br>
   BA - матрица не определена

   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;<br>

   AB - размерность $2\times 3$ <br>
   BA - матрица не определена

   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

   AB - размерность $8\times 8$ <br>
   BA - размерность $3\times 3$ <br>

   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

   AB - размерность $4\times 4$ <br>
   BA - размерность $4\times 4$ <br>

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [34]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

A  + B =  $\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ + $\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}.$

In [35]:
print(f'A + B = \n {a+b}')

A + B = 
 [[ 5 -3]
 [ 3  5]]


$A \times  B$ =  $\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ $\times  \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1 \cdot 4 + (-2) \cdot 0 & 1 \cdot (-1) + (-2) \cdot 5\\ 
3 \cdot 4 + 0 \cdot 0 & 3 \cdot (-1) + 0 \cdot 5
\end{pmatrix} = \begin{pmatrix}
4  & -11 \\ 
12  & -3
\end{pmatrix}$  

In [36]:
print(f'Матрица AB\n{a @ b}')

Матрица AB
[[  4 -11]
 [ 12  -3]]


$B \times  A$ =  $\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ $\times   \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} = \begin{pmatrix}
4 \cdot 1 + (-1) \cdot 3  & 4 \cdot (-2) + (-1) \cdot 0\\ 
0 \cdot 1 + 5 \cdot 3  & 0 \cdot (-2) + 5 \cdot 0
\end{pmatrix} = \begin{pmatrix}
1 & -8\\ 
15 & 0 
\end{pmatrix}$

In [37]:
print(f'Матрица BA\n{b @ a}')

Матрица BA
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [38]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

$3A-2B+4C = 3 \times \begin{pmatrix}
1 & 7\\ 
3  & -6
\end{pmatrix} - 2 \times \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4 \times \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3 & 21\\ 
9  & -18
\end{pmatrix} - \begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9  & -12
\end{pmatrix}.$

In [39]:
print(f'Матрица 3A - 2B + 4C \n{3 * a - 2 * b+ 4 * c}')

Матрица 3A - 2B + 4C 
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [40]:
a = np.array([[4, 1], [5, -2], [2, 3]])
a_t = a.T
print(f'Матрица A\n{a}')
print(f'Матрица A_T\n{a_t}')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Матрица A_T
[[ 4  5  2]
 [ 1 -2  3]]


$AA^{T} = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \times \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$

$AA^{T} = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \times \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
4 \cdot 4 + 1 \cdot 1 & 4 \cdot 5 + 1 \cdot (-2) & 4 \cdot 2 + 1 \cdot 3  \\ 
5 \cdot 4 + (-2) \cdot 1 & 5 \cdot 5 + (-2) \cdot (-2) & 5 \cdot 2 + (-2) \cdot 3  \\  
2 \cdot 4 + 3 \cdot 1 & 2 \cdot 5 + 3 \cdot (-2) & 2 \cdot 2 + 3 \cdot 3
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11 \\ 
18 & 29 & 4 \\  
11 & 4 & 13
\end{pmatrix}$

In [41]:
print(f'Матрица AxA_T\n{a @ a_t}')

Матрица AxA_T
[[17 18 11]
 [18 29  4]
 [11  4 13]]


$A^{T}A = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} \times \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2 & 4 \cdot 1 + 5 \cdot (-2) + 2 \cdot 3\\ 
1 \cdot 4 + (-2) \cdot 5 + 3 \cdot 2 & 1 \cdot 1 + (-2) \cdot (-2) + 3 \cdot 3\\
\end{pmatrix} = \begin{pmatrix}
45 & 0\\ 
0 & 14\\
\end{pmatrix}$

In [42]:
print(f'Матрица A_TxA\n{a_t @ a}')

Матрица A_TxA
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [63]:
A = np.array([[4, 1], [5, -2], [2, 3]])
B = a.T

In [64]:
def matrix_mult(A,B):
    a_c = A.shape[1] #кол-во столбцов матрицы А
    a_l = A.shape[0] #кол-во строк матрицы А
    b_c = B.shape[1] #кол-во столбцов матрицы В
    b_l = B.shape[0] #кол-во строк матрицы В
    if a_c != b_l:
        print(f'Вычислить произведение матриц A и B невозможно, поскольку число столбцов матрицы A = {a_c}, не совпадает с числом строк матрицы B = {b_l} ')
    else:
        C = [[0 for m in range(b_c)] for n in range(a_l)]
        for i in range(a_l):
            for j in range(b_c):
                for k in range(a_c):
                    C[i][j] += A[i][k] * B[k][j]
    return C

In [65]:
matrix_mult(A,B)

[[17, 18, 11], [18, 29, 4], [11, 4, 13]]

In [66]:
A @ B

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

## Матрицы и матричные операции. Часть 2

#### Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

#### __1.__ Вычислить определитель:

   a) $det$
$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}= sin^2x + cos^2x = 1$


   б) 𝑑𝑒𝑡
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}= 4 \cdot 5 \cdot 9 = 180  $

In [ ]:
B = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(B)

   в)

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1 \cdot \begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix}-
2\cdot\begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix}+
3\cdot\begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix} = 1 \cdot (5 \cdot 9  - 8 \cdot 6 ) - 2 \cdot (4 \cdot 9 - 6 \cdot 7) + 3 \cdot (4 \cdot 8 - 5 \cdot 7) = 0$

In [ ]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(C)

#### __2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2}) = 4^{2} = 16$;

   б) $det(A^{T}) = 4$; поскольку определитель транспонированной матрицы равен определителю исходной

   в) $det(2A)$ <br>
   $| \lambda \cdot A| = \lambda^{n} \cdot| A| $<br>
   $ 2^{rank(A)} \cdot det(A) = 2^{rank(A)} \cdot 4 = 2^{rank(A) +2}$

__3.__  Доказать, что матрица вырожденная.

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$
   
<br>
Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю. <br>
Согласно свойству 2, множитель строки (столбца) можно вынести за знак определителя. Вынеся таким образом множитель пропорциональности = -2 во второй строке, получим матрицу, имеющую две одинаковых строки 1 и 2. Согласно свойству 5, определитель такой матрицы равен нулю, матрица вырожденная

#### __4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$
Третья строка является суммой первой второй строк, а значит, ее можно отбросить, следовательно ранг матрицы равен 2

In [ ]:
A = np.matrix('1, 2, 3; 1, 1, 1; 2, 3, 4')
np.linalg.matrix_rank(A)


   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix};$Третья строка является суммой первой второй строк, а значит, ее можно отбросить, следовательно ранг матрицы равен 3

In [ ]:
B = np.matrix('0, 0, 2, 1; 0, 0, 2, 2; 0, 0, 4, 3; 2, 3, 5, 6')
np.linalg.matrix_rank(B)